### ISSUE TITLE
Issue with number of inputs to frame_sync block 

### ISSUE THREAD

**Issue by ask-gh** [tapparelj/gr-lora_sdr#108]
Hi,

Firstly, thanks for all the hard work!

I have managed to get everything up and running and working smoothly apart from one issue. Due to the number of inputs defined in the forecast of the frame sync block:

https://github.com/tapparelj/gr-lora_sdr/blob/b53a3ba434df3150f4fb51a3e4bb1226caa51717/lib/frame_sync_impl.cc#L121

when using larger SF values and/or lower BW (and hence a larger os_factor) the number of inputs becomes too large and I get the error message:

![image](https://github.com/user-attachments/assets/bcda9b44-85e4-454c-89b7-5c8e2f4ede18)

For reference, I am using the RTLSDR and the soapy RTLSDR source block.

Everything seems to working absolutely fine when the value of `ninput_items_required[0] < 8192` and also the rx_tx_functionality_check.grc works perfectly.

Any help with this would be much appreciated. Thanks

**Comment by tapparelj** [comment]
Hello @ask-gh,
This issue appears due to the default buffer size that GNU Radio allocates between blocks.
You should be able to fix it by checking #87 where I give more details.

Don't hesitate to let me know if you still can't fix it.

**Comment by ask-gh** [comment]
Thanks, this worked a charm!
