### ISSUE TITLE
Problem with SF 12 and 11 

### ISSUE THREAD

**Issue by rachida-saroui** [tapparelj/gr-lora_sdr#11]
Hello everyone, 

I have a problem when sitting SF to 12 or 11 in my RX flowgraph. It says that I don't have enough input data for the bloc frame_sync but I have no idea on how to resolve this.

Here is the error I get:
sched: <block frame_sync (5)> is requesting more input data
  than we can provide.
  ninput_items_required = 16392
  max_possible_items_available = 8191
  If this is a filter, consider reducing the number of taps.

Can anyone help me please? 
Thank you

**Comment by tapparelj** [comment]
Please refer to this issue: #10
