### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vAnArhist** [tapparelj/gr-lora_sdr#12]
Hello, I want to build module in WSL (Ubuntu 20.04). I installed gnu radio successfully, gnu-companion works ok.
Here is my version:  
```gnuradio-config-info --print-all```

> /usr/
> /etc
> /etc/gnuradio/conf.d
> /home/ivan/.gnuradio
> Wed, 02 Feb 2022 16:45:58Z
> testing-support;python-support;post-install;doxygen;man-pages;gnuradio-runtime;common-precompiled-headers;gr-ctrlport;* thrift;gnuradio-companion;gr-blocks;gr-fec;gr-fft;gr-filter;gr-analog;gr-digital;gr-dtv;gr-audio;* alsa;* oss;* jack;* portaudio;gr-channels;gr-pdu;gr-iio;* libad9361;gr-qtgui;gr-trellis;gr-uhd;gr-utils;gr_modtool;gr_blocktool;gr-video-sdl;gr-vocoder;* codec2;* freedv;* gsm;gr-wavelet;gr-zeromq;gr-network;gr-soapy
> 3.10.1.1
> cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software see the source for copying conditions.  There is NO
> warranty not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Copyright (C) 2019 Free Software Foundation, Inc.
> This is free software see the source for copying conditions.  There is NO
> warranty not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> /usr/bin/cc:::-O3 -DNDEBUG -g -O2 -fdebug-prefix-map=/build/gnuradio-8zZFH3/gnuradio-3.10.1.1-0~gnuradio~focal=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
> /usr/bin/c++:::-O3 -DNDEBUG -g -O2 -fdebug-prefix-map=/build/gnuradio-8zZFH3/gnuradio-3.10.1.1-0~gnuradio~focal=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fvisibility=hidden -Wsign-compare -Wall -Wno-uninitialized
> 2.4.3

Now i want to built gr-lora_sdr module, it Cmake shows me such info:

> Call Stack (most recent call first):
>   cmake/Modules/UseSWIG.cmake:256 (SWIG_ADD_SOURCE_TO_MODULE)
>   cmake/Modules/GrSwig.cmake:173 (SWIG_ADD_MODULE)
>   swig/CMakeLists.txt:49 (GR_SWIG_MAKE)
> 
> 
> CMake Error at cmake/Modules/GrSwig.cmake:211 (GR_LIBTOOL):
>   Unknown CMake command "GR_LIBTOOL".
> Call Stack (most recent call first):
>   swig/CMakeLists.txt:54 (GR_SWIG_INSTALL)
> 
> 
> -- Configuring incomplete, errors occurred!

How can I install this GR_LIBTOOL?

**Comment by joachimtapp** [comment]
Hello @vAnArhist,
I've never tried to build the module on gnuradio 3.10. Therefore, I'm not sure if the error comes from the gnuradio version or from some environment variable definition missing.
Can you try installing gnuradio version 3.8.2? There is a conda environment file in the root of the repository to easily create an environment with all dependencies.

Else you might have to port the module to the version you wish to use following
(https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide and https://wiki.gnuradio.org/index.php/GNU_Radio_3.10_OOT_Module_Porting_Guide)
