### ISSUE TITLE
Measured BER values

### ISSUE THREAD

**Issue by CharbelLahoud** [tapparelj/gr-lora_sdr#14]
Hi, is there any way to extract BER values?

**Comment by joachimtapp** [comment]
Hi @CharbelLahoud,
For now, there isn't a simple way to extract BER curves in GNU Radio. To obtain such curves, you will need to save the output of crc_verif to a file and process it. You can use the stream input of the whitening block to feed a file containing payload bytes, where frames are separated by carriage return.
