### ISSUE TITLE
Question about scaling Bandwidth/Spreading Factor

### ISSUE THREAD

**Issue by transcendent12** [tapparelj/gr-lora_sdr#16]
Hello,
I just wanted to ask whether parameters such as bandwidth/spreading factor are scalable beyond the standard protocol. e.g. Bandwidth >1MHz BW and larger spreading factors. Are these particularly constrained by physical properties or would they not give much extra performance with very low data rate requirements?

**Comment by tapparelj** [comment]
Hi, 
By quickly testing it, I found no issue using a sf greater than 12, or a different bandwidth. Spreading factors smaller than 7 won't work because the PHY header has to fit inside 8 LoRa symbols, which is just sufficent when using sf=7.
