### ISSUE TITLE
Simulating Tx and Rx doesn't seem to work with implicit header mode

### ISSUE THREAD

**Issue by VDelport** [tapparelj/gr-lora_sdr#20]
Hello,
if I run the flow graph tx_rx_simulation with impl_head = False, the payload of the transmitter arrives at the receiver. If I set impl_head = True it doesn't work. Is this a known problem?

**Comment by tapparelj** [comment]
Hi,
When using the implicit header mode, you should be sure that the coding rate and crc presence are the same between tx and rx, and that the frame length match the payload you want to transmitt
