### ISSUE TITLE
can't wait for update on v3.9

### ISSUE THREAD

**Issue by Burnwhite** [tapparelj/gr-lora_sdr#21]

**Comment by tapparelj** [comment]
I plan on pushing a new version of the receiver by the end of July. The idea was to move directly to gr 3.10, but I can try to leave a working branch on 3.9 if that is more convenient for you.

**Comment by tapparelj** [comment]
The module now supports gnuradio 3.10

**Comment by Burnwhite** [comment]
Thanks！
________________________________
发件人: tapparelj ***@***.***>
发送时间: Wednesday, August 3, 2022 10:31:34 AM
收件人: tapparelj/gr-lora_sdr ***@***.***>
抄送: Li Zongyao (PGR) ***@***.***>; Author ***@***.***>
主题: Re: [tapparelj/gr-lora_sdr] can't wait for update on v3.9 (Issue #21)


The module now supports gnuradio 3.10

―
