### ISSUE TITLE
Target sampling rate is not working

### ISSUE THREAD

**Issue by lahc1** [tapparelj/gr-lora_sdr#22]
I am trying to work with a sampling rate of 240 KHz and a bandwidth of 200 KHz, but the UHD is changing the sampling rate automatically to 480 KHz while compiling. Any suggestions how to fix this problem? and can we apply interpolation to the signal?

I am using USRP N321, a 10Gig ethernet, latest code branch.

**Comment by tapparelj** [comment]
Hi @lahc1,
as described [here](https://kb.ettus.com/N320/N321#Clocking_and_Sampling_Rates), you can't choose an arbitrary sampling rate on the USRP but you have to resample it yourself if you want a specific value. You can for example use the `Fractional Resampler` block, based on a resampling MMSE filter. Also, I am currently working on improving the selection of oversampling factors at both the transmitter and receiver. I will push it in the next few days, however, those will only be integer factors. Note that in the current implementation, an oversampling of four is required at the input of the `Frame sync` block.
