### ISSUE TITLE
Data in the Frame_sync Log Output

### ISSUE THREAD

**Issue by lemarquez** [tapparelj/gr-lora_sdr#28]
In the synchronization block (Frame_sync) there is the option Show_Log_Port=True, and its Documentation indicates:

"log: (Optional) Output the estimated value of SNR, CFO, STO, SFO, Off-by-one as a stream of float. Those values can be logged by a file_sink and read in an external application (MATLAB, Python, ...)"

However, the resulting txt file (the file_sink output) is unreadable and I have not found how to interpret the data type to extract the information neither with Matlab nor with Python.

Please guide me on how to treat the log output.

**Comment by tapparelj** [comment]
Hello, 
As an example, in matlab you could use 
```
f = fopen(['<log file name>']);
val = fread(f,'float');
fclose(f);

snr_est = val(1:5:end);
cfo_est = val(2:5:end);
sto_est = val(3:5:end);
sfo_est = val(4:5:end);
off_by_one_est = val(5:5:end);
```
