### ISSUE TITLE
tx_rx_functionnality_check with SF6 Header checksum invalid!

### ISSUE THREAD

**Issue by marktimmerman-dev** [tapparelj/gr-lora_sdr#29]
I use the master branch with gnuradio 3.10.4.0 (Python 3.8.10).

I copied the tx_rx_functionnality_check.grc example.
It works great with SF7.
Only thing I change is SF6.
Then it does not work anymore.

--------Header--------
Payload length: 14
CRC presence:   1
Coding rate:    0
Header checksum invalid!

When I change back to SF7, it works again.

Payload length: 14
CRC presence:   1
Coding rate:    0
Header checksum valid!

rx msg: Hello world: 0

CRC valid!

**Comment by tapparelj** [comment]
Hello @marktimmerman-dev,
The spreading factors lower than 7 can't use the explicit header mode, as indicated in the [datasheets](https://www.mouser.com/datasheet/2/761/sx1276-1278113.pdf) of the SX1276 (p.27).

**Comment by marktimmerman-dev** [comment]
OK. Thanks. It works with implicit header mode indeed. You can close the issue, as far as I'm concerned.

**Comment by tapparelj** [comment]
You're welcome, don't hesitate if you have other issues or questions.
