### ISSUE TITLE
CRC Issues about LDRO enabled packet transmits to SX1276

### ISSUE THREAD

**Issue by yangfengxu12** [tapparelj/gr-lora_sdr#32]
Hi, This is Fengxu. I discuss the issue when LDRO enabled packet transmission to SX1276.
I list some parameters used in communication between the TX node (USRP N210) running the lora_TX example and RX node (NUCLEO-476RG + sx1276mb1mas) running the Ping-pong example of STM32CubeExpansion_LRWAN_V1.3.1(ref:[https://www.st.com/en/embedded-software/i-cube-lrwan.html](https://www.st.com/en/embedded-software/i-cube-lrwan.html))
```
LoRa configurations:
Central frequency: 470MHz,
Bandwidth: 125KHz,
SF: 11, 12
LDRO: enabled,
CR: 1,
CRC: enabled
Explicit header
```
And here is the screenshot of the gr-lora.
![image](https://user-images.githubusercontent.com/38320739/198234697-1c86607d-f801-4391-9082-7dcf78c5ebb6.png)

After executing, the RX node prints the "OnRXError" via UART. This means the payload does not pass the CRC checking procedure according to the ST code comments.
![image](https://user-images.githubusercontent.com/38320739/198238178-d7ee96ac-57cb-40f4-bdf6-c50772a8af4f.png)

However, this issue disappears in the tx_rx_usrp example.
![image](https://user-images.githubusercontent.com/38320739/198241071-86943547-77c4-4823-ae8a-5c432f68eca5.png)

**Comment by tapparelj** [comment]
Hi @yangfengxu12,
Thanks for the details! I don't see many differences between the example lora_TX and tx_rx_usrp, except that the former has LDRO disabled by default. Just to be sure, did you changed it to "Auto" or "Enable" in the interleaver block?

**Comment by yangfengxu12** [comment]
Thanks, @tapparelj. I checked the parameters you mentioned. It is Disabled in lora_Tx by default. That's the main reason leading to this issue, thanks again.
