### ISSUE TITLE
SDR With sigfox STM32L0 Discovery kit LoRa as node.

### ISSUE THREAD

**Issue by Stianje** [tapparelj/gr-lora_sdr#37]
Hello,
I hope this post finds you well. I am currently working with an SDR and a STM node for testing purposes. I have been receiving packages through the RX chain, but have noticed that they are being flagged as "Header checksum invalid!". I have been trying to troubleshoot this issue by receiving the packages before the header check, and they are encrypted following the LoRaWAN documentation. I have successfully decrypted the package, but it does not seem to match the expected output. I was wondering if the RX chain in this repository follows the LoRaWAN documentation? Any insight or guidance would be greatly appreciated.

**Comment by tapparelj** [comment]
Hello @Stianje,
This repository only implement the LoRa physical layer, not the LoRaWAN MAC layer. 
If you send messages from a device following the LoRaWAN specifications, you should be able to detect the frame, decode the explicit header correctly and recover the payload, however the payload will contain a MAC header (prepend by LoRaWAN) and still be encrypted.
I'm surprised the header checksum test fails as it let me think the configuration you did is mostly correct as the preamble gets detected. 
If I remember correctly, LoRaWAN devices use the sync word 0x34. Did you set it up in the `frame sync` block?
Can you double check the spreading factor and the bandwidth you use at both the transmitter and receiver?

**Comment by Stianje** [comment]
Thanks for the quick response,
I have been testing for a bit and have not been able to resolve the issue with the header checksum. I am trying to use the SDR as a gateway and have it publish the data. I have the sync word setting in the Frame sync block is set to "0x3444". I am using the STM32 ICube end_node code for the node. As a beginner in this topic, I am having trouble locating the spreading factor and bandwidth settings in the STM code, but I believe they should be set to default values of SF7 and BW125k. 

GNU Radio Companion:
![Screenshot from 2023-01-26 13-32-32](https://user-images.githubusercontent.com/119126968/214836504-4ba65011-d450-4b62-b606-96fc34c0c84b.png)

Running w/ waterfall:
![Screenshot from 2023-01-26 13-34-43](https://user-images.githubusercontent.com/119126968/214836926-73847048-52d9-471f-8d9d-170e5e626cdd.png)

I would greatly appreciate any additional information or guidance you can provide on this issue.

**Comment by tapparelj** [comment]
I see a few things here:
- I've never had the chance to use a LoRa node using the 4Bytes sync word format (that your node seems to use given the value 0x3444 you want to use), can you set the sync word to 0x34 in the `frame sync` block as it should match the 0x3444 set in the STM node? This repo uses the 2 bytes format.
- The sample rate, bw and os factor configuration has some issue. If you use a sample rate of 2MHz in the `oscmocom source`, set the bandwidth to the same value. Next, in the `frame sync`, set the bandwidth to 125kHz(this is the LoRa signal bandwidth) and the os_factor to 8 (2MHz/125kHz). you can also remove the `samp_rate` variable if you don't use it.

Let me know if the issue changes

**Comment by Stianje** [comment]
Ok, thanks again for taking the time. 
I changed as you said.

This is the updated GNU:
![Screenshot from 2023-01-26 14-10-19](https://user-images.githubusercontent.com/119126968/214845138-2afe6a0e-f7c2-40cb-a9d5-7e61b60dc61f.png)

Updated results with frame sync block sync word 0x34:
![Screenshot from 2023-01-26 14-19-59](https://user-images.githubusercontent.com/119126968/214845631-68790734-340e-4ccb-b4a7-8abfae568029.png)
I do not get any output on this...

In the cmwx1zzabz_0xx.list STM32 file:
![image](https://user-images.githubusercontent.com/119126968/214846611-90e06700-8b7e-401c-a5f1-6e76b86959dc.png)

**Comment by tapparelj** [comment]
sorry, can you set the  os_factor to 16 not 8 (of course 2MHz/125kHz is not 8, my bad)

**Comment by Stianje** [comment]
No problem,
Still not any output...

Updated result:
![Screenshot from 2023-01-26 14-39-26](https://user-images.githubusercontent.com/119126968/214849981-da759eac-c4bb-45f0-aa4a-81b35ff7263c.png)

**Comment by tapparelj** [comment]
I am a bit surprised by the look of the waterfall, as nothing in it looks like a LoRa frame, but more like some FHSS modulation.
If you don't mind, could you use something like cubicSDR to have a good waterfall view of the spectrum?. (In order to check if what you transmit )

**Comment by tapparelj** [comment]
as an example this is the signal received for sf7 and sf12
![Screenshot from 2023-01-26 14-52-55](https://user-images.githubusercontent.com/66671413/214854351-8495dd0f-de37-4ab9-80f8-eb44df39de82.png)
![Screenshot from 2023-01-26 14-57-32](https://user-images.githubusercontent.com/66671413/214854358-ef3bcf4f-2b76-48d4-9e23-17efc0a927c1.png)

**Comment by Stianje** [comment]
I encountered some difficulties during the installation of CubicSDR. 
However, after some troubleshooting, I discovered that the problem seemed to stem from the spreading factor (sf) value in the STM code. It turns out that the default value for sf in the code is not SF7 as I initially assumed, but rather SF12. Once I made this correction, I noticed improvement. I will continue to work on this issue, but I wanted to share this information in case it helps others who may be facing the same problem. Based on my current understanding, does this solution seem correct to you?

Progress:
![Screenshot from 2023-01-26 16-53-27](https://user-images.githubusercontent.com/119126968/214885251-279fbd9d-4741-4dff-92f3-89ca226c704a.png)

A packet decoded:
![Screenshot from 2023-01-26 17-02-00](https://user-images.githubusercontent.com/119126968/214885704-70bc5a75-e378-47cb-a960-c3b39340760c.png)

**Comment by tapparelj** [comment]
Yes, the header is found and the checksum is correct. In addition if the CRC is valid, it means that you received the entire payload correctly. 
Then you have to decode the payload yourself as it's encoded by the MAC layer, which is not implemented in this repository for now.

**Comment by Stianje** [comment]
Thank you for your hard work and guidance. We were able to successfully resolve this.
I'm closing this issue now.
