### ISSUE TITLE
CRC locations

### ISSUE THREAD

**Issue by Frank012022** [tapparelj/gr-lora_sdr#38]
Hi!  Congratulations for this work!
I have a question on the CRC implementations. Per the diagram,  in TX, the CRC is calculated on whiten payload, while in RX the the CRC is verified after the de-whitening. Since the payload before/after whitening are different, will these have same CRC results?

Thanks

**Comment by tapparelj** [comment]
Hi @Frank012022,
the flowgraph is indeed a bit misleading. 
The CRC is computed using the non-whitened payload bytes but is itself not whitened.
Therefore the `add crc` block is computing the CRC based on the non-whitened payload sent as a tag alongside the whitened payload bytes.
At the transmitter, we chose to put this block after the `whitening`, as similarly to the header, the CRC is not whitened.
For the receiver, we placed it after the `dewhitening` as we need the dewhitened data to verify it.

Let me know if it is still confusing.
