### ISSUE TITLE
Help to understand the "cfo_frac" calculation process

### ISSUE THREAD

**Issue by Johnn13** [tapparelj/gr-lora_sdr#45]
Hello~ @tapparelj  
Thanks to your contribution.I have some question about your code during the process of calculating "cfo_frac".

question in codes:https://github.com/tapparelj/gr-lora_sdr/blob/870ea768560e1588cc1d3bb3011ebd9f40ef3e5f/lib/frame_sync_impl.cc#L234
https://github.com/tapparelj/gr-lora_sdr/blob/870ea768560e1588cc1d3bb3011ebd9f40ef3e5f/lib/frame_sync_impl.cc#L236

In the paper "Low Complexity LoRa Frame Synchronization for Ultra-Low Power Software-Defined Radios" Section 2.E, The author's calculation of "cfo_frac" is two consecutive preamble symbol, but you use several consecutive preamble symbols here to estimate the "cfo_frac",Why can you calculate the  "cfo_frac" by adding several phase differences and then using 
> -std::arg(four_cum) / 2 / M_PI;

in addition, In the paper, the "cfo_frac" is obtained by `BW(\phi_2-\phi_1)/N`,It seems that you haven't multiplied by `BW` and divided by `N` in your code.

**Comment by tapparelj** [comment]
Hello @Johnn13,
This might be indeed be confusing given the name of the function. The estimate uses the same principle as the one proposed by Bernier, but uses more symbols as proposed in "A Low-Complexity LoRa Synchronization Algorithm Robust to Sampling Time Offsets" Section IV A.
Regarding the sum:  intuitively, summing complex numbers which have the same arguments don't change that argument, only the magnitude. Here, each term of the sum has the same argument plus some noise added on top. For AWGN the noise will cancel itself out on average, whereas the signal will only add up leading to a better estimate of the original signal argument.
For the normalization, it comes from the definition of the fractional cfo, you can follow the paper I mention for more details.
I hope it clarified a bit your confusion. Let me know if something is still bothering you.
