### ISSUE TITLE
Dynamically changing the SF during runtime TX (modulate block bug)

### ISSUE THREAD

**Issue by Stianje** [tapparelj/gr-lora_sdr#46]
Hello,
I hope this message finds you well. We are currently working on the TX  experimenting with dynamically changing the SF during runtime.

We have tested each of the blocks individually, and they seem to function as expected. However, when we attempt to modify the SF of the modulating block while it is running, the transmission stops.

Do you have any experience or insights regarding this issue? Is it possible to achieve dynamic SF adjustment during runtime? Any advice or suggestions would be greatly appreciated.

Thank you for your time and assistance.

**Comment by tapparelj** [comment]
Hello @Stianje,
changing the spreading factor on the fly might require to add additional code to make sure the block has finished to process the previous frame before actually making the change. Another way might be to wait for the next frame_len tag (indicating the start of a new frame) to apply the change of SF to the block.

**Comment by Stianje** [comment]
Alright, thank you for your input. Closing this issue.
