### ISSUE TITLE
gr-lora_sdr  OOT  blocks doesn't appear in grc

### ISSUE THREAD

**Issue by abhmg** [tapparelj/gr-lora_sdr#54]
gr-lora_sdr  OOT  blocks doesn't appear in GRC 3.10.5.1 , and also created config.conf and path but doesn't works give me a solution for this.

**Comment by tapparelj** [comment]
Hello @abhmg,

I'm certain we can fix that issue. But I would need some additional information.
- Can you give some details on how you installed gnuradio (e.g. via pybombs, conda, from source,...) ?
- When you open gnuradio-companion, is the path you added to the config.conf listed in the terminal part of grc?
- When building this module, is there any errors? and when using `make install`, is the path mentioned as the installation path the one you expect?
