### ISSUE TITLE
replace USRP block with RTL SDR

### ISSUE THREAD

**Issue by sajadmathe** [tapparelj/gr-lora_sdr#57]
Hi
I am a new in gnuradio.
I replaced USRP block with RTL SDR block in lora_RX.grc.
![Screenshot from 2023-08-20 06-57-55](https://github.com/tapparelj/gr-lora_sdr/assets/138300874/8159fed0-68e1-4976-97e1-b31fca7afd9c)

when i run lora_RX.grc flowgraph in GNURadio i see this outpot:

![Screenshot from 2023-08-20 06-21-07](https://github.com/tapparelj/gr-lora_sdr/assets/138300874/eed987b4-0b34-4aff-9e9b-ddc5594ee07d)

I don't understand anything from this output. Can you guide me?

thanx

**Comment by tapparelj** [comment]
Hi @sajadmathe,
Based on the error, it seems that the SDR you are using doesn't support a sample rate of 125kHz. To know which rates it supports, try searching in its datasheets.
If it supports any multiple of 125kHz, you can simply add a _Keep one in N_ block to decimate the signal. Else you might need to use a _Fractional resampler_ or a _Rational resampler_.

In addition, I see some errors with the parameters you set in the block:
- The _Sample rate_ should be set to the variable _samp_rate_ (you can use variables in flowgraphs). The example uses an oversampling factor of 4 (that I would recommend to keep) to synchronize, hence being set to 500kHz for a LoRa bandwidth (_bw_) of 125kHz. 
- The _Frequency_ should be set to the variable _center_freq_. This variable of course needs to match the frequency used by your transmitter.

If you are new to gnuradio, try having a look at the tutorials [here](https://wiki.gnuradio.org/index.php?title=Tutorials) to get familiar with the main concepts of flowgraphs.

**Comment by tapparelj** [comment]
I'll close this issue as there has been no follow-up in the past two months, but feel free to reopen it if needed.
