### ISSUE TITLE
setpaths

### ISSUE THREAD

**Issue by davidcastells** [tapparelj/gr-lora_sdr#6]
In gr-lora_sdr/apps/README.txt you refer to setpaths.sh which is no longer there.

In my Ubuntu 18.04 system my library binaries end up in 
~/miniconda3/lib/x86_64-linux-gnu/libgnuradio-lora_sdr.so

But command line python fails to include that path by default.
What should be done?

**Comment by tapparelj** [comment]
Sorry about that line in this ReadMe, it should have been removed.
When building the module , cmake will install the library in the active conda environment or PyBombs prefix if possible. With conda, the paths should be set automatically when activating the environment. However, if the path are still missing you have to set both the variables PYTHONPATH and LD_LIBRARY_PATH as described here https://wiki.gnuradio.org/index.php/ModuleNotFoundError. If you want to install the library in a different path, you can set it with the parameter -DCMAKE_INSTALL_PREFIX when executing cmake.

**Comment by davidcastells** [comment]
thanks
