### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by coolkingcole** [tapparelj/gr-lora_sdr#63]
I've been having a lot of problems getting an environment set up for this. I've solved some of the issues, but still get errors. Is there anyway that you could make a docker that is representative of your environment?

**Comment by tapparelj** [comment]
Hello @coolkingcole,
I have no experience with docker, but the environment.yml file contains a conda environment compatible. Maybe it might be useful. From my experience most dependencies are directly installed alongside gnuradio. 
Can you give more information about your issues?
