### ISSUE TITLE
coding rate and numbering

### ISSUE THREAD

**Issue by nkaramolegos** [tapparelj/gr-lora_sdr#64]
Is 0 coding rate the 4/5 or uncoded?

**Comment by tapparelj** [comment]
Hi @nkaramolegos,
the codjng rate is defined as for the commercial chips meaning that the rate is 4/(4+CR).
So 0 will be uncoded.
Based on the datasheets CR0 is not supported by commercial chips, but by trying it they still seems to accept this option.
