### ISSUE TITLE
can’t recv LLCC68 message

### ISSUE THREAD

**Issue by 11tools** [tapparelj/gr-lora_sdr#90]
[]
![recv](https://github.com/tapparelj/gr-lora_sdr/assets/29034846/1debd4ee-a6fd-45d5-be57-e71234a7fcfb)

I use  hackrf and plutosdr make this. Both. Them can't recv LLCC68 mod

**Comment by tapparelj** [comment]
Hello @11tools,

from your screenshot I can't notice anything strange, therefore, I would guess that there is a configuration mismatch between the transmitter and receiver. So here are a few questions:
- Is the tx_rx_functionality_check.grc flowgraph working?
- is the frame visible on the waterfall sink? (using a larger spreading factor may help seeing it)
- what is the sync word used by your module? (cf datasheets)
![image](https://github.com/tapparelj/gr-lora_sdr/assets/66671413/943c4a0b-0fcd-420b-9b7e-8eeaf34f7872)
- If you save the samples you receive in a file and then plot their instantaneous frequency can you see the chirps (when the transmitter is close to your receiver to get a large SNR)?

**Comment by 11tools** [comment]
Hello @tapparelj .

  Thanks . I changed the Spreading factor to 8,9,10,11,12... still failed no message. maybe the sync word is difference

  I had made a flow with Lora Tx and a Lora Rx on PlutoSDR. it can recv message what Lora Tx send.

  My real goal is use gr-lora_sdr to recv startlink 150M Lora signal. because 150M lora module is hard to buy. 
   
  have anyone try this?

**Comment by tapparelj** [comment]
As it has been some time without follow-up with more information on your setup/problem, I'll close the issue. Don't hesitate to reopen it if needed.
