### ISSUE TITLE
Can't decode a signal

### ISSUE THREAD

**Issue by DANTEKSTUDIO** [tapparelj/gr-lora_sdr#97]
Hi, thanks for this awesome project!
I use RTL SDR V3 Pro and Vega Smart-MC0101 but I can't get any symbols.

tx_rx_functionality_check is working:
![image](https://github.com/tapparelj/gr-lora_sdr/assets/59147174/261e0d48-637b-4e9b-b6c0-f4b21aa511df)

My GNU Radio project:
![image](https://github.com/tapparelj/gr-lora_sdr/assets/59147174/250a13f0-1870-46c2-8e22-f11db1359f84)

My waterfall:
![image](https://github.com/tapparelj/gr-lora_sdr/assets/59147174/5e8a0f22-a651-481b-952e-2cf2fc84f250)

My LoRa device setup:
![image](https://github.com/tapparelj/gr-lora_sdr/assets/59147174/7e17164c-8c01-4a78-b9f6-a4f8189912c6)
![image](https://github.com/tapparelj/gr-lora_sdr/assets/59147174/e2a41f46-5814-4d20-8178-83e08bba6531)

**Comment by DANTEKSTUDIO** [comment]
It works, but I get wrong CRC.

Send packet: 01 63 00 0E 01 02 02 69 CF 6B 66

GNU Radio console:

--------Header--------
Payload length: 24
CRC presence:   1
Coding rate:    1
Header checksum valid!

rx msg: 0x80, 0x2b, 0x8, 0x44, 0x0, 0xc, 0x31, 0x0, 0x52, 0xe4, 0x74, 0xd9, 0x26, 0x2a, 0xf3, 0x7, 0x14, 0x63, 0x84, 0x62, 0xd8, 0x93, 0x1d, 0x37
[31mCRC invalid[0m

**Comment by tapparelj** [comment]
Hello,
given that your device uses the sync word 0x34 and that the received payload is longer than what you send, your devices seems to send data using the LoRaWAN MAC layer.
You might want to have a look at [this issue](https://github.com/tapparelj/gr-lora_sdr/issues/95#issuecomment-2110414937) to get more details on what this repo can (and can not do).
Regarding the CRC error, can you try to use a different option for the LDRO  in the _header decoder_ block (if it's on AUTO try disabling it, or set it to AUTO if it was disabled)?

**Comment by DANTEKSTUDIO** [comment]
And the last question. I know AppKey and NwkKey. Can I decode bytes of LoRaWAN (the MAC layer of LoRa) using a python block?

**Comment by tapparelj** [comment]
Hello,
unfortunately I'm not aware of a python implementation of the MAC frame decoding.
I currently have a version of a transmitter that can send LoRaWAN frames using ABP, however, there is no downlink support yet.
I will publish the code for the transmitter early July. I can keep you updated if it interests you.

**Comment by DANTEKSTUDIO** [comment]
[tapparelj](https://github.com/tapparelj), thanks for everything. I'll definitely keep an eye on the progress of the project.

**Comment by DANTEKSTUDIO** [comment]
Hello, @tapparelj.
What about the transmitter? When we can test it?

**Comment by tapparelj** [comment]
Hello @DANTEKSTUDIO,
sorry for the longer than expected delay. The code for LoRaWAN Tx is available [here](https://github.com/tapparelj/gr-lorawan). There was some change to the phy layer to support the transmission so you will need to update your installation of gr-lora_sdr as well.

For now, the transmissions are limited to the EU bands, but adding support for other bands should not be too hard.
Let me know if you encounter any difficulties or problems.

**Comment by tapparelj** [comment]
I'll close the issue as this repo only implements the physical layer of LoRa, so the MAC layer implementation is not an issue of the implementation.
