### ISSUE TITLE
To decode .wav file in Tapparel flowgraph

### ISSUE THREAD

**Issue by ppjilab** [tapparelj/gr-lora_sdr#99]
Good Evening Sir,
we are working on your flowgraph to decode the .wav file of LoRa signal.
![Screenshot from 2024-07-11 18-13-14](https://github.com/tapparelj/gr-lora_sdr/assets/175317008/0e2750ce-fff6-4e4d-8fc3-4aa23bab0972)

**Comment by ppjilab** [comment]
Sir, please resolve our issue that how to decode .wav file in your flowgraph.

**Comment by tapparelj** [comment]
Hello @ppjilab,
I can only help if you provide some context to your problem.
All I see here is a flowgraph for the receiver connected to a wav source...

**Comment by tapparelj** [comment]
As it has been some time without follow-up, I'll close the issue.
